"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,Users,Target,ReceiptText,RefreshCw,Plus,Search} from "lucide-react";

type Dept={id:string;code:string;name:string}; type Emp={id:string;name:string;company:string;department:Dept;status:string};
const seed:Emp[]=[
["Black+Decker","ياسمين احمد عبدالوهاب","SDA"],["Smart","بسنت محمد سيد","SDA"],["Casil","هشام محمد قرني","SDA"],["Incia","ميرنا اشرف سعيد","SDA"],["Mienta","ندي سيد احمد عوض علي","SDA"],["HERVY","سمر صلاح عبدالحميد","SDA"],
["Kiriazi","ايهاب سلامه محمد","MDA"],["Midea","رضا محمد محمد مصطفي","MDA"],["Royal Gas","سيف ماجد محمد","MDA"],["Fresh","احمد حسين محمد","MDA"],["Bosch","احمد عادل صادق","MDA"],["El Araby","سعيد عبدالعظيم عبدالتواب","MDA"],["El Araby","مجدي ابراهيم محمد","MDA"],["Zanussi","زهراء محمد عبدالتواب صابر","MDA"],
["Vivo","محمد يونس","MOBILE"],["Realme","هشام ايمن","MOBILE"],["Joyroom","تسنيم اسماعيل علي","MOBILE"],["Oppo","حسام ابراهيم","MOBILE"],["Samsung","محمد مجدي","MOBILE"],["Samsung","علي شعبان","MOBILE"],["Vivo","عمر حسين","MOBILE"],["Xiaomi","عمرو عويس","MOBILE"],
["Hisense","محمود حسين مسعود","TV-AC"],["Haier","فاطمه مصطفي حسين","TV-AC"],["Samsung","يوسف سامي يوسف","TV-AC"]].map(([company,name,code],i)=>({id:String(i+1),name,company,department:{id:code,code,name:code},status:"ACTIVE"}));
const departments=["ALL","TV-AC","MDA","MOBILE","SDA"];
export default function Home(){const [employees,setEmployees]=useState<Emp[]>(seed);const [dept,setDept]=useState("ALL");const [q,setQ]=useState("");const [year,setYear]=useState(new Date().getFullYear());const [month,setMonth]=useState(new Date().getMonth()+1);const [loading,setLoading]=useState(true);const [monthReady,setMonthReady]=useState(false);
useEffect(()=>{setLoading(true);setMonthReady(false);fetch("/api/month?year="+year+"&month="+month).then(r=>r.ok?r.json():null).then(d=>{if(d?.employees?.length)setEmployees(d.employees);setMonthReady(!!d)}).catch(()=>{}).finally(()=>setLoading(false))},[year,month]);
const visible=useMemo(()=>employees.filter(e=>(dept==="ALL"||e.department.code===dept)&&(e.name+" "+e.company).toLowerCase().includes(q.toLowerCase())),[employees,dept,q]);
return <main><header><div><span className="eyebrow">SALES OPERATIONS</span><h1>Promoters Performance</h1><p>Target, sales and invoice performance dashboard</p></div><button className="primary" onClick={()=>location.reload()}><RefreshCw size={17}/> Refresh</button></header>
<section className="toolbar"><select value={year} onChange={e=>setYear(+e.target.value)}><option>2026</option><option>2027</option><option>2028</option></select><select value={month} onChange={e=>setMonth(+e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2000,i,1).toLocaleString("en",{month:"long"})}</option>)}</select><div className="search"><Search size={17}/><input placeholder="Search promoter or company..." value={q} onChange={e=>setQ(e.target.value)}/></div></section>
<nav className="tabs">{departments.map(d=><button key={d} className={dept===d?"active":""} onClick={()=>setDept(d)}>{d}</button>)}</nav>
<section className="cards"><K icon={<Users/>} label="Promoters" value={visible.length}/><K icon={<Target/>} label="Monthly Target" value="0"/><K icon={<ReceiptText/>} label="Invoices" value="0"/><K icon={<BarChart3/>} label="Actual Sales" value="0"/></section>
<section className="monthbar"><strong>{monthReady?"Monthly cycle ready":"Preparing month..."}</strong><span>Each year/month is stored independently. Previous months remain unchanged.</span></section><section className="panel"><div className="panelhead"><div><h2>Promoter Performance</h2><span>{year} · {new Date(2000,month-1,1).toLocaleString("en",{month:"long"})}</span></div><button className="secondary"><Plus size={16}/> Add Promoter</button></div><div className="tablewrap"><table><thead><tr><th>Promoter</th><th>Company</th><th>Department</th><th>Target</th><th>Actual</th><th>Achievement</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Loading...</td></tr>:visible.map(e=><tr key={e.id}><td className="name">{e.name}</td><td>{e.company}</td><td><span className="badge">{e.department.code}</span></td><td>0</td><td>0</td><td><span className="percent danger">0%</span></td></tr>)}</tbody></table></div></section></main>}
function K({icon,label,value}:{icon:React.ReactNode;label:string;value:React.ReactNode}){return <div className="card"><span className="icon">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}